# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ImageList' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!


  target 'ImageListTests' do
    inherit! :search_paths
    # Pods for testing
  end

   target 'ImageListUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'HGSegmentedPageViewController'
pod 'WechatOpenSDK'
pod 'YYKit'
pod 'MJExtension'
pod 'Masonry'
pod 'MJRefresh'
pod 'Toast'
pod 'IQKeyboardManager'
pod 'Reachability'
pod 'DZNEmptyDataSet'
pod 'SVProgressHUD'
pod 'RKNotificationHub'
pod 'LCActionSheet'
pod 'SDWebImage/GIF'
pod 'AFNetworking'
pod 'FLAnimatedImage'
end
